.\" Manpage for prep.
.\" Contact ryan@micrantha.com to correct errors or typos.
.TH prep 1 "15 Feb 2018" "1.0" "prep man page"
.SH NAME
prep \- package manager and build tool for C/C++ projects
.SH SYNOPSIS
.B [-v] [-h] [-f] [-g]
.SH DESCRIPTION
.B prep
is a modular package manager and build tool for C/C++ projects. 

A package.json defines dependencies and how to resolve and build them using plugins.

It is still in beta.
.SH OPTIONS
.IP -v
display output in verbose mode
.IP -h
display help
.IP -f
force an action without caching
.IP -g
use the global repository
.SH SEE ALSO
prep-package(1), prep-plugin(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Ryan Jennings (ryan@coda.life)

