#!/usr/bin/env perl

use rlib '../support';
use rj::prep::plugin qw(read_build_params);

sub autoconf
{
    my ($package, $version, $sourcePath, $buildPath, $installPath, $buildOpts) = read_build_params;

    my $configure = $sourcePath . "/configure";

    if ( ! -e $configure ) {
        chdir($sourcePath);

        my $autogen = $sourcePath . "/autogen.sh";

        if ( ! -e $autogen ) {
            print("Don't know how to build $package... no autotools configuration found.");
            return PREP_FAILURE;
        }

        system($autogen);

        if ( $? != 0) {
            return 1;
        }

        if (! -e $configure) {
            print("Could not generate a configure script for $package");
            return PREP_FAILURE;
        }
    }

    exec $configure, "--prefix=$installPath", $buildOpts
}

sub main
{
    my $plugin = rj::prep::plugin->new();

    $plugin->on_build(\&autoconf);

    return $plugin->execute();
}

exit(&main);
