#!/usr/bin/env perl

use rlib '../support';
use rj::prep::plugin qw(read_build_params);

sub make
{
	my $self = shift;
    my ($package, $version, $sourcePath, $buildPath, $installPath, $buildOpts) = read_build_params;

    chdir($buildPath);

    exec "make", "-j2", "install"
}

sub main
{
	my $plugin = rj::prep::plugin->new();

	$plugin->on_build(\&make);

    return $plugin->execute();
}

exit(&main);
