#!/usr/bin/env perl

use File::Basename;
use CPAN;

sub install_dependencies
{
	$CPAN::Config->{use_prompt_default} = true;

    my $file = dirname($0) . "/../support/cpan_modules.txt";

    open my $fp, $file or die "could not open $file";

    while(my $line = <$fp>) {
        CPAN::Shell->install($line);
    }

    return 0;
}

sub main
{
	my $param = <STDIN>;

    chomp($param);

    if ($param eq "load") {
    	return install_dependencies();
    }
    return 1;
}

exit(&main);