#!/usr/bin/env perl

use rlib '../support';
use Archive::Extract;
use File::Fetch;
use rj::prep::plugin qw(get_param get_resolve_params);

sub extract
{
    my ($path, $location) = get_resolve_params;

    my $file = File::Fetch->new( uri => $location );

    if (!$file) {
        return 1;
    }

    my $archive = $file->fetch( to => $path );

    if (!$archive) {
        return 1;
    }

    my $ae = Archive::Extract->new( archive => $archive );

    if (!$ae->extract( to => $path )) {
        return 1;
    }

    print "RETURN " . $ae->extract_path . "\n";
    
    return 0;
}

sub main
{
    my $command = get_param;

    if ($command eq "resolve") {
        return extract;
    }

    return 1;
}

exit(&main);
