#!/usr/bin/env perl

use lib '../support';
use Archive::Extract;
use rj::prep::plugin qw(get_param get_package_params);
use File::Temp qw/ :mktemp  /;

sub extract
{
    my ($package, $version, $path, $config) = get_package_params;

    my $ae = Archive::Extract->new( archive => $package );

    $tmpdir = mkdtemp( '/tmp/prep-XXXXXX' );

    if (!$ae->extract( to => $tmpdir )) {
        return 1;
    }

    exec "brew", "install", $package
}

sub main
{
    my $command = get_param;

    if ($command eq "build") {
        return extract;
    }

    return 1;
}

exit(&main);
