#!/usr/bin/env perl

use rlib '../support';
use Archive::Extract;
use File::Fetch;
use micrantha::prep::plugin qw(read_resolve_params write_return_value);

sub extract
{
    my ($path, $location) = read_resolve_params;

    if (not defined $path or length($path) == 0 or not defined $location or length($location) == 0) {
        return PREP_FAILURE;
    }

    my $file = File::Fetch->new( uri => $location );

    if (!$file) {
        return PREP_FAILURE;
    }

    my $archive = $file->fetch( to => $path );

    if (!$archive) {
        print "Unable to fetch $location to $path\n";
        return PREP_FAILURE;
    }

    my $ae = Archive::Extract->new( archive => $archive );

    if (!$ae->extract( to => $path )) {
        print "Unable to extract $archive to $path\n";
        return PREP_FAILURE;
    }

    write_return_value($ae->extract_path);

    return PREP_SUCCESS;
}

sub main
{
    my $plugin = micrantha::prep::plugin->new();

    $plugin->on_resolve(\&extract);

    return $plugin->execute();
}

exit(&main);
