#!/usr/bin/env perl

use rlib '../support';
use rj::prep::plugin qw(read_package_params);

sub tap
{
    exec "brew", "tap", "homebrew/versions"
}

sub install
{
    my ($package, $version) = read_package_params;

    #todo version support
    #my $result = `brew versions $package`
    #my $commit = cut -d ' ' -f 4
    #my $formula = cut -d ' ' -f 5
    #brew unlink $package

    exec "brew", "install", $package
}

sub remove
{
    my ($package, $version) = read_package_params;

    exec "brew", "remove", $package
}

sub main
{
    my $plugin = rj::prep::plugin->new();

    $plugin->on_load(\&tap);
    $plugin->on_install(\&install);
    $plugin->on_remove(\&remove);

    return $plugin->execute();
}

exit(&main);
