#!/usr/bin/env perl

use rlib '../support';
use micrantha::prep::plugin qw(read_build_params);
use strict;
use warnings;

sub cmake
{
    my ($package, $version, $sourcePath, $buildPath, $installPath, $buildOpts) = read_build_params;

    chdir($buildPath);

    exec "cmake", "-DCMAKE_INSTALL_PREFIX=$installPath", $buildOpts, $sourcePath
}

sub main
{
    my $plugin = micrantha::prep::plugin->new();

    $plugin->on_build(\&cmake);

    return $plugin->execute();
}

exit(&main);
